# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=30)),
                ('agency_url', models.CharField(max_length=30)),
                ('agency_timezone', models.CharField(max_length=30)),
                ('agency_lang', models.CharField(max_length=30)),
                ('agency_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('service_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.IntegerField()),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=12)),
                ('route_long_name', models.CharField(max_length=50)),
                ('route_type', models.IntegerField()),
                ('route_color', models.CharField(max_length=12)),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=30)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('location_type', models.IntegerField()),
                ('parent_station', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpp.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Stop_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.CharField(max_length=12)),
                ('departure_time', models.CharField(max_length=12)),
                ('stop_sequence', models.PositiveIntegerField()),
                ('pickup_type', models.PositiveSmallIntegerField()),
                ('drop_off_type', models.PositiveSmallIntegerField()),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trip_headsign', models.CharField(max_length=30)),
                ('wheelchair_accessible', models.IntegerField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Route')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Calendar')),
                ('shape_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Shape')),
            ],
        ),
        migrations.AddField(
            model_name='stop_time',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpp.Trip'),
        ),
    ]
