# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0002_auto_20170514_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='shape_id',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
