# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0003_auto_20170514_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('shape_pt_lat', models.FloatField()),
                ('shape_pt_lon', models.FloatField()),
                ('shape_pt_sequence', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='shape_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dpp.Shape'),
            preserve_default=False,
        ),
    ]
