# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0004_auto_20170514_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='parent_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dpp.Stop'),
        ),
    ]
