# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0005_auto_20170515_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='agency_id',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='stop_time',
            old_name='stop_id',
            new_name='stop',
        ),
        migrations.RenameField(
            model_name='stop_time',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='shape_id',
            new_name='shape',
        ),
    ]
