# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpp', '0007_remove_trip_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_long_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stop',
            name='parent_station',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(max_length=100),
        ),
    ]
