# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_testing', '0002_auto_20170521_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='successFail',
            new_name='success',
        ),
        migrations.AddField(
            model_name='experiment',
            name='targetAddress',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'ReverseGeocoding'), (2, 'PoiAddress'), (3, 'PoiMhd'), (4, 'GpsCompass')], default=0),
        ),
    ]
