# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviterier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='houseNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='address',
            name='landRegistryNumber',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shape',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shape',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
