# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviterier', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
