# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviterier', '0002_auto_20170510_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='houseNumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='landRegistryNumber',
            field=models.CharField(max_length=30),
        ),
    ]
